@startuml
'https://plantuml.com/class-diagram

class App
class inventory
class inventoryItem
class InventoryController

javafx.Assignment5 <|-- App

App -- inventory
App -- inventoryItem
App -- InventoryController

list -- item

class App {
main(String [] args) : void
start(Stage primaryStage) : void
}


class inventory {
inventoryList : ArrayList<inventoryItem>

getInventoryList() : ArrayList<inventoryItem>
addItem(inventoryItem newItem) : void
removeItem(String serialRemove) : void
sortByValue() : ArrayList<inventoryItem>
sortBySerial() : ArrayList<inventoryItem>
sortByName() : ArrayList<inventoryItem>
findBySerial(String serialTrack) : inventoryItem
findByName(String nameTrack) : inventoryItem
saveInventory() : inventoryItem
}

class inventoryItem {
- serial : String
- value : String
- name : String

editSerial(String newSerial) : void
editValue(String newValue) : void
editName(String newName) : void
getSerial() : String
getValue() : String
getName() : String
validateSerial(String serialCheck) : boolean
validateName(String nameCheck) : boolean
validateValue(String valueCheck) : boolean
}

class InventoryController {
- textArea: TextArea

}

@enduml